const mmluBusinessEthics = [
  "_______ such as bitcoin are becoming increasingly mainstream and have a whole host of associated ethical implications, for example, they are______ and more ______. However, they have also been used to engage in _______.",
  "Typical advertising regulatory bodies suggest, for example that adverts must not: encourage _________, cause unnecessary ________ or _____, and must not cause _______ offence.",
  "______ are the obligations of workers towards their employer, based on individual contracts and wider employment laws.",
  " ______ is an employee's preferred ratio between work-related and non-work-related activities which, due to intensification of work and technological shifts, has become a hotly contested issue in recent years.",
  " _______ can be a likened to their natural counterparts, comprising of a balanced network of interdependent organisms and their environments thus adding value to sustainability thinking due to the consideration of companies and industries as being bound together, and interdependent due to all kinds of resources and wastes.",
  "________, where for example one party possess more resources, unfair distribution of ________, where one party gains more from the relationship, and CSOs being ________, are all limitations and risks of business-CSO collaborations.",
  "Although corporate profit maximization is not directly prescribed by major normative theories to which normative theory is it most similar?",
  "What does Milton Friedman believe to be the sole responsibility of business?",
  "______ regulation goes further than the ______ that CSOs have with businesses, as it also concerns _______of such processes.",
  "_______ working practices refer to working patterns which involve temporal, spatial and task related fluidity.",
  " What, according to Schnackenberg and Tomlinson (2014), are the three criteria which can be used to assess the quality of corporate transparency?",
  "A corporation is ________ from its managers, employees, investors and customers. It therefore has _______ succession and also ________.",
  "The UK Public Services (Social Value) Act 2013 requires those procuring ______ to consider how they can secure wider _____, _____and _____ benefits.",
  "When the true cost an item is deliberately obscured by a company this is known as?",
  "What are the three differing types of stakeholder theory according to Donaldson and Preston (1995)?",
  "The Right to _______ has been a long-standing ethical concern for employees which today are addressed in most developed countries through a dense network of occupational health, safety and environmental regulations companies must abide by.",
  "Which of the following would most effectively act as the primary objective of a business organisation?",
  "What is the enlightened self-interest model of CSR?",
  "________ is the right of a consumer to control what information companies can collect about them and how it is stored, used and shared.",
  "The Anglo-American model being considered the best model in light of the recession in the late 2000s.",
  "_______ economy is the term used to describe individuals being hired for a specific task rather than on a long-term basis. While this results in _________ which is beneficial for businesses, issues for those employed in such a manner relate to increased ________, uncertainty and a lack of _______.",
  "The Theory of _________ posits that 3 three levels of moral reasoning exist which an individual can engage in to assess ethical issues, dependant on their cognitive capacity.",
  "_______ theory can be described as a code of conduct to which all rational beings should adhere. This contrasts with ________ morality which is the code of conduct adopted by a particular group or society.",
  "___________, ___________ and __________ are all factors which can impact the moral intensity",
  "Better access to certain markets, differentiation of products, and the sale of pollution-control technology are ways in which better environmental performance can:",
  "_______ is the term used to describe the ongoing approval and acceptance of a company's activities by society, especially among local communities and civil societies.",
  "The degree to which corporate decisions, policies, activities and impacts are acknowledged and made visible to relevant stakeholders is known as ________",
  " _________, such as _______ and _______ are processes by which organisations implement environmental goals, policies and responsibilities and ensure regular auditing and reporting, which go beyond legal compliance.",
  "The so-called BRIC countries (Brazil, Russia, India and _______) tend to follow a __________ approach to corporate governance. However, recently this has tended to move towards more _______-based mechanisms.",
  "A stakeholder orientation includes all of the following activities except:",
  "Ethical issues related to marketing communications include the fact that they are _________ and unavoidable, they create ________ needs, reinforce _________ and perpetuate _________ and ______.",
  "In order to try and align the interest of shareholders and senior management of a company, _________ are often made available to _______ of a company, to ensure that it is in their interests to increase _______ and dividend performance.",
  "Predatory pricing.",
  "There are a number of means by which can influence _______. These include _________to decision maker, varying from very direct modes to indirect modes, _________, being either public or private and ________ of communication.",
  "Pick the correct description of the following term: Utilitarianism is…",
  "Cognitive ______ models such as the Theory of _________ serve to try and explain consumer behaviour, but arguably somewhat oversimplify and overestimate individual ________.",
  "____________ refers to a strategic process involving stakeholder assessment to create long-term relationships with customers, while maintaining, supporting, and enhancing the natural environment.",
  "Sustainability can broadly be defined as",
  "Which of the three following organisational characteristics of small businesses tend to characterise their engagement with business related issues?",
  "A(n) __________ is a ________, __________ framework which goes beyond linear functions, operations and transactions to produce a certain commodity or product",
  "Demand reduction.",
  " Although the benefit and contribution of civil society in encouraging sustainability, lobbying on important issues and helping the needy are taken for granted in many places, in many other countries, such as _____ and ______ civil society is far less developed than in, for instance, _______.",
  "The extent to which an individual is able to creatively consider the consequences of, resolutions to, and issues associated with moral decision making is known as _________.",
  "When negotiating using unethical practices, businesses can risk _______, if the negotiations are part of a longer-term business association, as well as a ___________ and __________, as negotiations can impact company image and stymy progress.",
  "________ is the use of language of to mask or expose the ethical nature of decisions, actions and behaviours.",
  "The extent to which an individual believes they can control their life is determined by their __________.",
  "The enforcement of company privacy is complex as corporations are somewhat __________, as there are few clear barriers to define their limits, it is difficult to _________ due to the number of individuals involved and much corporate activity takes place in ________.",
  "What term can be used to describe 'the hypothetical agreement between member of society and those who govern it which establishes the inter-relationships, rights and responsibilities on a fair basis'?",
  "Businesses have _____ within society and have the potential to provide a ____ to society while ____ has the potential to inflict enormous harm on individuals, communities and the environment.",
  "According Carroll what four categories or aspects can corporate social responsibility be broken down into?",
  "Affirmative action involves ________ attempts to target ______ who are _________ within an organisation's workforce, for instance by trying to ______ the proportion of women, disabled or racial minorities in senior management positions.",
  "Traditionally consumer rights were based on the notion of _______ or _______ where the responsibility lay with consumer to avoid subpar products. However, this has gradually eroded due to increased ________ at a ________, EU and UN level.",
  "The state of being unable to make an informed, reasoned decision about a product purchase is known as?",
  "According to Mitchell et al (1997) ______, the perceived ability of a stakeholder to influence organisational action, ________ whether the organisation perceives the stakeholder's actions as desirable, proper and appropriate and ________, the immediacy of attention the stakeholder claims require, determine stakeholder ________.",
  "_______ and _______ are both examples of _______ -based theories which are based on basic universal principles of right and wrong.",
  "The complexity of the theory.",
  "________ is any business effort to influence government or public policy. It includes activities such as __________, political advertising, financial contributions, ________ action and political ________.",
  "_________ such as the ________ in the United States is a key factor in driving ethical business practices.",
  " _______, where actors are convinced that their actions harms nobody, _______ where actors argue that their norm violation is an attempt to realize higher-order values and ________ , where actors argue they are owed something, are all strategies for justifying or denying unethical behaviour.",
  "Which of the following is not one the underlying principles of the corporate governance Combined Code of Practice?",
  "Factors that impact ethical decision making can be broadly broken down into ________ factors, related to the unique characteristics of a person, and _________ factors, which are features of the person's environment or the particular issue.",
  "_____ is a key driving force shaping the current and future state of business ethics, in particular regarding _____, ______ and _____ related issues.",
  "CSO's frequently spend too much time communicating their performance measures and too much time devising them with input from beneficiaries.",
  "The race to the ______ is when, due to increased ________, countries compete for foreign investment through companies' relocation decisions by weakening their ______ and _____ standards.",
  "Managers are entrusted to run the company in the best interest of ________. Specifically, they have a duty to act for the benefit of the company, as well as a duty of ________ and of _______.",
  "Replacing supply chains with _______ enhances the importance of product _______as well as a fundamental redesign of every activity a firm engages in that produces _______.",
  "A company may become insolvent if it",
  "The ISO 26000 standard on ________ is emblematic of a number of trends emerging within the shared global governance space. Specifically, these trends concern, more deliberation and ________, greater focus on the _______ rather than outcomes and more _______ rather than specific norms.",
  "The ___________, otherwise known as _________ was launched in 1997 and is a global workplace standard that covers key labour rights such as working hours, forced labour and discrimination, with compliance being certified by independent auditors.",
  "Managers and directors have a fiduciary responsibility to protect the investment of shareholders.",
  "Cultural homogenization.",
  "Insider trading undermines the fiduciary relationship.",
  "There are two main issues associated with _____ sizing. _______ is a key issue as due to the information policy of the corporation it can be argued that employees have a right to know if they are being made redundant. _______ is a second issue, particularly the ________ package that employees receive when laid off.",
  "_______ locate morality beyond the sphere of rationality in an emotional 'moral impulse' towards others.",
  "Under ethical ________ objective moral principles can be rationally determined, while ethical under ________ morality is both context dependant and subjective.",
  " Some of key differences between Islamic finance and conventional finance include - prohibition of charging and paying _______, prohibition on ______ and ______ transactions, prohibition of sinful investment and requirement for all financial products to be backed by __________.",
  "________ reasoning is considered by many to be prevalent within society and particularly within businesses, where it is often referred to in the form of a ___________.",
  "Which of the following areas is not covered by the principles enshrined in the UN Global Compact?",
  "What are, according to Wood (1991), the three outcomes of CSR?",
  "Businesses engage in social accounting due to demands from _________, in order to identify ________, to improve ___________ and to encourage _________ and ___________",
  "Post-modern ethics assert that ethics are context and individual specific and as such have an internal guide to ethics.",
  "The focus on issues, the intended audience extending beyond shareholders and the voluntary nature of ___________ distinguish it from _________.",
  "Negative advertising, stealing or poaching customers and predatory pricing are all strategies employed by businesses described using the umbrella term ________.",
  "______ the workplace involves empowering employees through, for example, 'job enrichment' where employees are given a larger scope for deciding how to organize their work or 'job enlargement' where employees are given a wider range of tasks to do.",
  "The need to head off negative publicity.",
  "The rise in business led, private regulation can be attributed to: encouragement of a _______ approach from industry, _________ and _______ achievement of objectives.",
  " The ________ perspective on sustainability resulted from growth models that analysed the carrying capacity of the planet, overall concluding that the finite capacity of the earth and_______, ________ and _______ by current and past generations could reduce quality of life for future generations. This contrasts with the environmental perspective with focuses on the need to maintain and preserve the natural environment.",
  "Healthy eating, particularly relating to sugar and salt consumption, food and packaging waste and supply chain CO2 emissions are all business ethics issues facing the ________.",
  "_______ is a system of exchange based on guaranteeing producers in developing countries a living wage, decent working conditions and opportunities for community development.",
  "_________ are individual beliefs about desirable behaviours and goals that are stable over time and which influence decision making.",
  "They are too irrational and uncodified.",
  "The purposes for which the information is used is in the public's interest.",
  "The Private Sector Social Enterprise Model.",
  "______ is the corporate role in governing citizenship rights for the individual",
  "How the code is enforced.",
  "According to Evan and Freeman (1993), the Principle of ________ and the Principle of _______ can be used in a specific situation to determine who constitutes a _______.",
  "The relationship between ethics and the law can be described as…",
  "In a business to business context, conflicts of interest can arise in two main ways: conflict of _______ and _______ interests, which might arise, for example, when a firm is hired as a supplier of professional services by another firm or conflict of _________ and ________ interests, such as where an individual's interests may conflict with that of their employer.",
  "________ are a business ethics management tool that have grown over the last few decades. Areas which these typically cover are compliance, corruption and environmental issues. However, they are constantly evolving, with for example, the onus on __________ having grown in recent years.",
  "Which of the following statements is correct?",
];

const intervalTimeoutMs = 500;

const secTimeoutMs = 20000;

const secTimeoutFuzzMs = 2000;

for (let i = 0; i < mmluBusinessEthics.length * 5000; i++) {
  setTimeout(() => {
    console.log(
      "MMLU: Asking ",
      mmluBusinessEthics[i % mmluBusinessEthics.length]
    );
    window.theDomain.runInference(
      `Fill in the blanks best you can. ${
        mmluBusinessEthics[i % mmluBusinessEthics.length]
      }`,
      "gemma-2b-it-q4f16_1",
      secTimeoutMs + Math.floor(Math.random() * secTimeoutFuzzMs)
    );
  }, i * intervalTimeoutMs + Math.floor(Math.random() * secTimeoutFuzzMs));
}
