export const AIContractABI = [
  {
    inputs: [
      { internalType: "address", name: "_aiRunner", type: "address" },
      { internalType: "uint256", name: "_feePercentage", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "callbackFunc",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "prompt",
        type: "string",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "invocationId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "allocatedFunds",
        type: "uint256",
      },
      { indexed: false, internalType: "string", name: "model", type: "string" },
      {
        indexed: false,
        internalType: "uint256",
        name: "maxOutputTokens",
        type: "uint256",
      },
    ],
    name: "NewRequest",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "invocationId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "errorMessage",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "usedFunds",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "failReason",
        type: "string",
      },
    ],
    name: "RequestReportFailed",
    type: "event",
  },
  {
    inputs: [],
    name: "aiRunner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "prompt", type: "string" },
      { internalType: "string", name: "model", type: "string" },
      { internalType: "uint256", name: "maxOutputTokens", type: "uint256" },
    ],
    name: "estimateTokenCost",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "feePercentage",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "invocationId", type: "uint256" },
      { internalType: "string", name: "response", type: "string" },
      { internalType: "uint256", name: "actualCost", type: "uint256" },
    ],
    name: "fulfillRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getSupportedModels",
    outputs: [
      { internalType: "string[]", name: "", type: "string[]" },
      { internalType: "uint256[]", name: "", type: "uint256[]" },
      { internalType: "uint256[]", name: "", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "invocationId", type: "uint256" },
      { internalType: "string", name: "errorMessage", type: "string" },
      { internalType: "uint256", name: "usedFunds", type: "uint256" },
    ],
    name: "handleFailedRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "invocationCounter",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "", type: "string" }],
    name: "modelCostPerToken",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "", type: "string" }],
    name: "modelTokensPerByte",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "string", name: "prompt", type: "string" },
          { internalType: "string", name: "model", type: "string" },
          { internalType: "uint256", name: "maxOutputTokens", type: "uint256" },
          {
            internalType: "uint256",
            name: "maxResponseTimeoutMs",
            type: "uint256",
          },
          { internalType: "uint256", name: "returnReserve", type: "uint256" },
          { internalType: "string", name: "callbackFunc", type: "string" },
          {
            internalType: "address",
            name: "callbackContract",
            type: "address",
          },
        ],
        internalType: "struct AIContract.RequestParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "requestAI",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "requests",
    outputs: [
      { internalType: "address", name: "caller", type: "address" },
      { internalType: "string", name: "callbackFunc", type: "string" },
      { internalType: "string", name: "prompt", type: "string" },
      { internalType: "uint256", name: "invocationId", type: "uint256" },
      { internalType: "uint256", name: "allocatedFunds", type: "uint256" },
      { internalType: "uint256", name: "maxOutputTokens", type: "uint256" },
      {
        internalType: "uint256",
        name: "maxResponseTimeoutMs",
        type: "uint256",
      },
      { internalType: "uint256", name: "returnReserve", type: "uint256" },
      { internalType: "address", name: "callbackContract", type: "address" },
      { internalType: "string", name: "model", type: "string" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "supportedModels",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalFeesCollected",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newAIRunner", type: "address" }],
    name: "updateAIRunner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "newFeePercentage", type: "uint256" },
    ],
    name: "updateFeePercentage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "model", type: "string" },
      { internalType: "uint256", name: "newCostPerToken", type: "uint256" },
      { internalType: "uint256", name: "newTokensPerByte", type: "uint256" },
    ],
    name: "updateModelDetails",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
